server:
  port: ${HTTP_PORT:8080}

spring:
  application:
    name: distributed-key-value-store
  grpc:
    server:
      port: ${GRPC_PORT:9090}

springdoc:
  api-docs:
    enabled: true
    path: /docs/openapi
    groups:
      enabled: true
  swagger-ui:
    path: /docs

seed:
  ip: ${SEED_IP:}
  port: ${SEED_PORT:0}
